# Generated by Django 4.2.6 on 2023-10-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('add_user', 'Can Add New User Info'), ('view_user', 'Can View User Info'), ('change_user', 'Can Change User Info'), ('delete_user', 'Can Delete User'))},
        ),
    ]
