# Generated by Django 4.2.6 on 2023-10-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminuser_manageruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='ManagerUser',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
