# Generated by Django 4.2.6 on 2023-10-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('calories', models.IntegerField(help_text='Total Number of calories in an entry')),
            ],
        ),
    ]
