# Generated by Django 4.2.6 on 2023-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id']},
        ),
    ]
